[package]
build = 'build.rs'
edition = '2018'
name = 'ton_vm'
version = '1.8.38'

[dependencies]
ed25519 = '1.2'
ed25519-dalek = '1.0'
failure = '0.1'
hex = '0.4'
lazy_static = '1.4'
log = '0.4'
num = '0.4'
num-traits = '0.2'
rand = '0.7'
sha2 = '0.9'
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.11.2' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', tag = '1.7.51' }

criterion = { features = [ 'html_reports' ], version = '0.3' }
ton_labs_assembler = { git = 'https://github.com/tonlabs/ton-labs-assembler.git', tag = '1.2.42' }
#rug = '1.14' # for rug-bigint benchmark

[features]
ci_run = [  ]
fift_check = [  ]
log_file = [  ]
verbose = [  ]

[lib]
bench = false

[profile.bench]
debug = true

[[bench]]
name = "benchmarks"
harness = false
